version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"  # Workflow files stored in the default location of `.github/workflows`
    schedule:
      interval: "weekly"

  # rust
  - package-ecosystem: "cargo"
    directory: "/fast_aug"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # python
  - package-ecosystem: "pip"
    directory: "/bindings/python"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "cargo"
    directory: "/bindings/python"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
