mod base;
mod chars_random_delete;
mod chars_random_insert;
mod chars_random_substitute;
mod chars_random_swap;
mod utils;
mod words_random_delete;
mod words_random_insert;
mod words_random_substitute;
mod words_random_swap;

pub use base::BaseTextAugmenter;
pub use chars_random_delete::CharsRandomDeleteAugmenter;
pub use chars_random_insert::CharsRandomInsertAugmenter;
pub use chars_random_substitute::CharsRandomSubstituteAugmenter;
pub use chars_random_swap::CharsRandomSwapAugmenter;
pub use utils::{Doc, TextAugmentParameters, Token, TokenType};
pub use words_random_delete::WordsRandomDeleteAugmenter;
pub use words_random_insert::WordsRandomInsertAugmenter;
pub use words_random_substitute::WordsRandomSubstituteAugmenter;
pub use words_random_swap::WordsRandomSwapAugmenter;
