name: Test Python bindings

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  RUST_BACKTRACE: full


jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Cache rust
        uses: Swatinem/rust-cache@v2
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Make bindings/python/.venv/bin/python softlink to global python
        run: |
          mkdir -p bindings/python/.venv/bin
          ln -s $(which python) bindings/python/.venv/bin/python
      - name: Build and install package
        run: make build-python
      - name: Run linters
        run: make lint-python

  test-python:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    #        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.12]
    #       python-version: [3.8, 3.9, 3.10, 3.11, 3.12]
        debug: [true, false]  # test with a debug build as it picks up errors which optimised release builds do not
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Cache rust
        uses: Swatinem/rust-cache@v2
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Make bindings/python/.venv/bin/python softlink to global python
        run: |
          mkdir -p bindings/python/.venv/bin
          ln -s $(which python) bindings/python/.venv/bin/python
      - name: Run rust tests in debug=${{ matrix.debug }} mode
        run: |
          if ${{ matrix.debug }}; then
            make test-python BUILD_PROFILE=dev
          else
            make test-python BUILD_PROFILE=release
          fi

  profile-python:
#    runs-on: ubuntu-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Cache rust
        uses: Swatinem/rust-cache@v2
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Make bindings/python/.venv/bin/python softlink to global python
        run: |
          mkdir -p bindings/python/.venv/bin
          ln -s $(which python) bindings/python/.venv/bin/python
#      - name: Install pref
#        run: |
#          sudo apt-get update
#          sudo apt-get install linux-tools-common linux-tools-generic linux-tools-`uname -r`

#      - name: Check Kernel Version
#        run: uname -a
#      - name: Verify perf Installation
#        run: perf --version
#      - name: Test perf
#        run: sudo perf list
#      - name: Simple perf Test
#        run: sudo perf stat ls
#      - name: Check Virtualization
#        run: |
#          grep -cw vmx /proc/cpuinfo || echo "No VMX support. Might be running in a VM without virtualization extensions."

      - name: Run profiling in release mode
        run: make profile-python
      - name: Upload profiling results
        uses: actions/upload-artifact@v4
        with:
          name: python-profiling-results
          path: |
            # benchmarking results and flamegraph
            bindings/python/*.svg
          if-no-files-found: error